"""Create team management tables

Revision ID: 004
Revises: 003_create_user_first_last_names.py
Create Date: 2026-01-25 18:55:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite3

# revision identifiers
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create roles table
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('display_name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('permissions', sa.JSON(), nullable=True),
        sa.Column('is_system_role', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'])
    
    # Create team_members table
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('department', sa.String(length=100), nullable=False),
        sa.Column('specialization', sa.String(length=200), nullable=True),
        sa.Column('bio', sa.Text(), nullable=True),
        sa.Column('avatar_url', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('hire_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tasks_completed', sa.Integer(), nullable=True),
        sa.Column('average_rating', sa.Integer(), nullable=True),
        sa.Column('total_projects', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users'], ['id'], ),
        sa.ForeignKeyConstraint(['role_id'], ['roles'], ['id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'])
    op.create_index(op.f('ix_team_members_role_id'), 'team_members', ['role_id'])
    
    # Create tasks table
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('task_type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('priority', sa.String(length=20), nullable=True),
        sa.Column('character_id', sa.Integer(), nullable=True),
        sa.Column('assigned_to_id', sa.Integer(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.Column('reviewer_id', sa.Integer(), nullable=True),
        sa.Column('script_id', sa.String(length=100), nullable=True),
        sa.Column('voice_id', sa.String(length=100), nullable=True),
        sa.Column('animation_id', sa.String(length=100), nullable=True),
        sa.Column('motion_graphics_id', sa.String(length=100), nullable=True),
        sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('estimated_hours', sa.Integer(), nullable=True),
        sa.Column('actual_hours', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('attachments', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['character_id'], ['islamic_characters'], ['id'], ),
        sa.ForeignKeyConstraint(['assigned_to_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['created_by_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['reviewer_id'], ['team_members'], ['id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_character_id'), 'tasks', ['character_id'])
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'])
    op.create_index(op.f('ix_tasks_created_by_id'), 'tasks', ['created_by_id'])
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'])
    
    # Create projects table
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('priority', sa.String(length=20), nullable=True),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('estimated_completion', sa.DateTime(timezone=True), nullable=True),
        sa.Column('project_manager_id', sa.Integer(), nullable=True),
        sa.Column('team_members', sa.JSON(), nullable=True),
        sa.Column('total_tasks', sa.Integer(), nullable=True),
        sa.Column('completed_tasks', sa.Integer(), nullable=True),
        sa.Column('budget', sa.Integer(), nullable=True),
        sa.Column('actual_cost', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['project_manager_id'], ['team_members'], ['id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'])
    op.create_index(op.f('ix_projects_project_manager_id'), 'projects', ['project_manager_id'])
    
    # Create content_approvals table
    op.create_table('content_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content_type', sa.String(length=50), nullable=False),
        sa.Column('content_id', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('submitted_by_id', sa.Integer(), nullable=True),
        sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
        sa.Column('current_stage', sa.String(length=50), nullable=True),
        sa.Column('feedback', sa.Text(), nullable=True),
        sa.Column('revision_notes', sa.Text(), nullable=True),
        sa.Column('approval_notes', sa.Text(), nullable=True),
        sa.Column('submission_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('final_approval_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['submitted_by_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['reviewed_by_id'], ['team_members'], ['id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_approvals_content_type'), 'content_approvals', ['content_type'])
    op.create_index(op.f('ix_content_approvals_status'), 'content_approvals', ['status'])
    
    # Insert default roles
    op.execute("""
        INSERT INTO roles (name, display_name, description, permissions, is_system_role) VALUES
        ('super_admin', 'Super Admin', 'Full system access and control', '["CREATE_CHARACTER", "EDIT_CHARACTER", "DELETE_CHARACTER", "CREATE_SCRIPT", "EDIT_SCRIPT", "APPROVE_SCRIPT", "UPLOAD_VOICE", "EDIT_VOICE", "APPROVE_VOICE", "UPLOAD_ANIMATION", "EDIT_ANIMATION", "APPROVE_ANIMATION", "UPLOAD_MOTION_GRAPHICS", "EDIT_MOTION_GRAPHICS", "APPROVE_MOTION_GRAPHICS", "MANAGE_TEAM", "ASSIGN_TASKS", "VIEW_ANALYTICS", "SYSTEM_CONFIG", "USER_MANAGEMENT"]', true),
        ('content_manager', 'Content Manager', 'Manage all content creation workflows', '["CREATE_CHARACTER", "EDIT_CHARACTER", "CREATE_SCRIPT", "EDIT_SCRIPT", "APPROVE_SCRIPT", "UPLOAD_VOICE", "APPROVE_VOICE", "UPLOAD_ANIMATION", "APPROVE_ANIMATION", "UPLOAD_MOTION_GRAPHICS", "APPROVE_MOTION_GRAPHICS", "VIEW_ANALYTICS"]', false),
        ('script_writer', 'Script Writer', 'Write and edit scripts for characters', '["CREATE_SCRIPT", "EDIT_SCRIPT"]', false),
        ('voice_artist', 'Voice Artist', 'Record and edit voice content', '["UPLOAD_VOICE", "EDIT_VOICE"]', false),
        ('animator', 'Animator', 'Create and edit animations', '["UPLOAD_ANIMATION", "EDIT_ANIMATION"]', false),
        ('motion_graphics', 'Motion Graphics Designer', 'Create and edit motion graphics', '["UPLOAD_MOTION_GRAPHICS", "EDIT_MOTION_GRAPHICS"]', false),
        ('reviewer', 'Content Reviewer', 'Review and approve content', '["APPROVE_SCRIPT", "APPROVE_VOICE", "APPROVE_ANIMATION", "APPROVE_MOTION_GRAPHICS"]', false)
    """))

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_approvals')
    op.drop_table('projects')
    op.drop_table('tasks')
    op.drop_table('team_members')
    op.drop_table('roles')
